apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: odoo-gateway
  namespace: odoo
spec:
  gatewayClassName: traefik
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: "walidb.fr"
    allowedRoutes:
      namespaces:
        from: Same
